name: demo
root: .
enable_pane_titles: true

windows:
  - main:
      layout: main-vertical
      panes:
        - dpu:
          - sshpass -p YourPaSsWoRd ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 admin@10.250.0.55
        - npu:
          - sshpass -p password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 admin@10.250.0.101
        - ptf:
          - docker exec -it ptf_vms6-1 bash
        - mgmt:
          - docker exec -it mgmt bash
